{
  "phases": {
    "setup": {
      "nixPkgs": ["nodejs-18_x"]
    },
    "install": {
      "cmds": ["cd server && npm ci"]
    },
    "build": {
      "cmds": ["echo 'No build step required'"]
    },
    "start": {
      "cmd": "cd server && npm start"
    }
  }
}
